#nullable enable
using System;
using UShell.Runtime.Core.Suggestions;

namespace UShell.Runtime.Core.Commands
{
	/// <summary>
	/// Represents a fully configured parameter required or accepted by a command.
	/// </summary>
	/// <remarks>
	/// This is a read-only data structure generated by the <see cref="UShell.Runtime.Core.Commands.Fluent.ICommandConfigurator"/>.
	/// </remarks>
	public sealed class CommandParameter
	{
		/// <summary>
		/// The name of the parameter. Used for named argument binding (e.g., <c>-name</c>).
		/// </summary>
		public string Name { get; }

		/// <summary>
		/// The underlying .NET Type expected by the execution delegate.
		/// </summary>
		public Type ParameterType { get; }

		/// <summary>
		/// Indicates whether this parameter can be safely omitted by the user.
		/// </summary>
		public bool IsOptional { get; }

		/// <summary>
		/// The fallback value injected during execution if <see cref="IsOptional"/> is <c>true</c> 
		/// and the user does not provide the argument.
		/// </summary>
		public object? DefaultValue { get; }

		/// <summary>
		/// The provider responsible for yielding autocomplete suggestions for this specific parameter.
		/// </summary>
		public ISuggestionProvider? SuggestionProvider { get; }

		/// <summary>
		/// Initializes a new instance of the <see cref="CommandParameter"/> class.
		/// </summary>
		public CommandParameter(string name, Type parameterType, bool isOptional, object? defaultValue, ISuggestionProvider? suggestionProvider = null)
		{
			if (string.IsNullOrWhiteSpace(name))
			{
				throw new ArgumentException("Parameter name cannot be empty.", nameof(name));
			}

			Name = name;
			ParameterType = parameterType ?? throw new ArgumentNullException(nameof(parameterType));
			IsOptional = isOptional;
			DefaultValue = defaultValue;
			SuggestionProvider = suggestionProvider;
		}
	}
}