namespace UShell.Runtime.Core.Output.Formatting
{
	/// <summary>
	/// Defines the visual border style for ASCII tables generated by the shell.
	/// </summary>
	public enum TableStyle : byte
	{
		/// <summary>Draws a separator line only beneath the headers.</summary>
		Standard = 0,

		/// <summary>Draws horizontal separator lines between every row.</summary>
		Grid = 1
	}
}